config/routes.rb
Rails.application.routes.draw do
  get 'orders/show/:id', to: 'order#show', as: 'show_order'
  get 'orders/food_item/new/:food_item_id', to: 'orders#new', as: 'new_order_food_item'
  post 'orders/create', to: 'orders#create', as: 'create_order'

  get 'food/show/:id', to: 'food#show', as: 'show_food'

  get 'welcome/menu'
  get 'welcome/contact'

  root 'welcome#menu'
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_many :food_items, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :food_item

  validates :name, :phone, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'application'
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def show
    @food_item = FoodItem.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
  end

  def new
    @order = Order.new
    @order.food_item_id = params[:food_item_id]
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      render :show
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone, :address, :food_item_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def menu
    @menu_items = MenuItem.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food/show.html.erb
<div class="col-md-8">
  <div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <%= @food_item.name %>
          <span class="badge pull-right"><%= @food_item.price %> VND</span>
        </h3>
      </div>
      <div class="panel-content">
        <br/>
        <img src="<%= @food_item.image_url %>" class="img-responsive"/>
        <br/>
      </div>
      <div class="panel-footer text-center">
        <p><%= @food_item.description %></p>
        <%= link_to 'Order', new_order_food_item_path(@food_item.id), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <%= link_to 'Restaurant', root_path %>
      </li>
      <li>
        <%= link_to 'Menu', welcome_menu_path %>
      </li>
      <li>
        <%= link_to 'Contact Us', welcome_contact_path %>
      </li>
    </ul>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>
  <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

</body>
</html>

app/views/orders/new.html.erb
<div class="col-sm-8">
  <div class="card">
    <%= form_for(@order, url: create_order_path, method: :post) do |f| %>
        <div class="card-block">
          <% if @order.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h2><%= pluralize(@order.errors.count, "error") %> prohibited this article from being saved:</h2>
                <ul>
                  <% @order.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          
          <fieldset class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.label :phone %><br>
            <%= f.text_field :phone %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.label :address %><br>
            <%= f.text_area :address %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.label :food_item_id %><br>
            <%= f.text_field :food_item_id, readonly: true %>
          </fieldset>
        </div>
        <div class="card-footer">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="col-md-8">
  <div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Thank you for your order page</h3>
      </div>
      <div class="panel-content">
        <br/>
        <ul>
          <li>Name: <%= @order.name %></li>
          <li>Phone: <%= @order.phone %></li>
          <li>Address: <%= @order.address %></li>
          <li>Food Item: <%= @order.food_item.name %></li>
          <li>Process Date: <%= Time.now.strftime('%A, %B %e, %H:%M') %></li>
        </ul>
        <br/>
      </div>
      <div class="panel-footer text-center">
        <p><strong>Total: </strong><%= @order.food_item.price %></p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/contact.html.erb
<div class="col-md-12">
  <div>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3>Contact Information</h3>
      </div>
      <div class="panel-content text-center">
        <br/>
        <p><span class="glyphicon glyphicon-home"></span>    200 West Thomas St. Seattle, WA 98119</p>
        <p><span class="glyphicon glyphicon-earphone"></span>    +1 (206) 455-9424</p>
        <hr/>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d688466.8465548515!2d-122.92015352139498!3d47.61984024874558!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5490155b532c3a47%3A0xc3caa82ce0fa681b!2sTINYpulse!5e0!3m2!1sen!2s!4v1449374625414" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/welcome/menu.html.erb
<div class="col-md-6">
  <div id="menu">
    <div class="panel list-group">
      <% @menu_items.each do |menu_item| %>
        <a href="#" class="list-group-item" data-toggle="collapse" data-target="#<%= menu_item.name.downcase %>" data-parent="#menu">
          <strong><%= menu_item.name %></strong>
        </a>
        <div id="<%= menu_item.name.downcase %>" class="sublinks collapse">
          <% menu_item.food_items.each do |food_item| %>
            <a href="<%= show_food_path(food_item.id) %>" class="list-group-item small">
              <input type="hidden" value="<%= food_item.id %>"/>
              <span class="glyphicon glyphicon-chevron-right"></span> <%= food_item.name %>
              <span class="badge pull-right"><%= food_item.price %> VND</span>
            </a>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>